name: Windows

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          choco install swig
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        shell: powershell

      - name: Clone PyInstaller
        uses: actions/checkout@v2
        with:
          repository: pyinstaller/pyinstaller
          ref: 40c9abce2d8de879e414fd377c933dccaab1e156
          path: pyinstaller

      - name: Build PyInstaller
        shell: bash
        run: |
          cd pyinstaller/bootloader
          python waf distclean all
          cd ..
          pip install .
          cd ..

      - name: Build exe
        shell: bash
        run: |
          pyinstaller authventure.spec

      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: yubico-authventure-windows
          path: dist
